name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Create-Application-Properties:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ./src/main/resources
      - run: cd ./src/main/resources
      - run: touch ./application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties